import datetime
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.orm import relationship
from app.db.base_class import Base

class DBWorkflow(Base):
    """
    Represents a full multi-agent orchestration workflow instance.
    Tracks state progress, user ownership, and timing characteristics.
    """
    __tablename__ = "workflows"

    id = Column(String, primary_key=True, index=True)  # UUID or custom workflow ID
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    name = Column(String, nullable=False)              # e.g., "Build RAG Chatbot"
    status = Column(String, default="pending")         # "pending", "running", "completed", "failed"
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    tasks = relationship("DBAgentTask", back_populates="workflow", cascade="all, delete-orphan")
    logs = relationship("DBWorkflowLog", back_populates="workflow", cascade="all, delete-orphan")
    history = relationship("DBWorkflowHistory", back_populates="workflow", cascade="all, delete-orphan")


class DBAgent(Base):
    """
    Agent registry. Stores system descriptions and specialized guidelines
    for each role: planner, research, coding, reviewer, documentation.
    """
    __tablename__ = "agents"

    id = Column(String, primary_key=True, index=True)   # "planner", "research", "coder", "reviewer", "documentation"
    name = Column(String, nullable=False)               # Friendly name e.g., "Software Engineer Agent"
    role = Column(String, nullable=False)               # CS specialized role title
    system_prompt = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class DBAgentTask(Base):
    """
    Represents a specific sub-task delegated to an agent within an active workflow execution.
    """
    __tablename__ = "agent_tasks"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    workflow_id = Column(String, ForeignKey("workflows.id", ondelete="CASCADE"), index=True, nullable=False)
    agent_id = Column(String, index=True, nullable=False)  # Target agent ID e.g. "planner"
    task_description = Column(Text, nullable=False)
    status = Column(String, default="pending")             # "pending", "running", "completed", "failed"
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    workflow = relationship("DBWorkflow", back_populates="tasks")
    outputs = relationship("DBAgentOutput", back_populates="task", cascade="all, delete-orphan")


class DBAgentOutput(Base):
    """
    Stores structured artifacts generated by agents during workflow executions.
    """
    __tablename__ = "agent_outputs"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    task_id = Column(Integer, ForeignKey("agent_tasks.id", ondelete="CASCADE"), index=True, nullable=False)
    output_type = Column(String, nullable=False)           # "plan", "research_notes", "code", "review_report", "documentation"
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    task = relationship("DBAgentTask", back_populates="outputs")


class DBWorkflowLog(Base):
    """
    Unified chronological event log tracking step-by-step agent decisions,
    internal thoughts, loops, and routing signals.
    """
    __tablename__ = "workflow_logs"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    workflow_id = Column(String, ForeignKey("workflows.id", ondelete="CASCADE"), index=True, nullable=False)
    agent_id = Column(String, nullable=True)               # Which agent emitted this log, if any
    message = Column(Text, nullable=False)
    log_level = Column(String, default="info")             # "info", "warning", "error", "debug"
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    workflow = relationship("DBWorkflow", back_populates="logs")


class DBWorkflowHistory(Base):
    """
    Historical summaries of finished execution stats, used for dashboard listings.
    """
    __tablename__ = "workflow_history"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    workflow_id = Column(String, ForeignKey("workflows.id", ondelete="CASCADE"), index=True, nullable=False)
    summary = Column(Text, nullable=True)
    result_status = Column(String, nullable=False)         # "completed", "failed"
    duration_seconds = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    workflow = relationship("DBWorkflow", back_populates="history")
